// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
}

type OAuth2Client = {
  id: string
  applicationType: string
  grantTypes: string[]
  tokenEndpointAuthMethod: string[]

  name: string
  allowedCorsOrigins: string[]
  scopes: string[]
  audiences: string[]
  redirectUris: string[]
  postLogoutRedirectUris: string[]

  contacts: string[]
  uri?: string
  policyUri?: string
  tosUri?: string
  logoUri?: string
}

type TestIdClient = {
  clientId: string
  clientSecret: string
  client: OAuth2Client
}

type Client = {
  client: OAuth2Client
  testIdClient?: TestIdClient
  url: string
}
