// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {} // eslint-disable-line

// https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationResponse

type ApplicationType = 'spa' | 'webApplication' | 'mobileApplication' | 'desktopApplication' | 'machineToMachine' | 'cli' | 'smartTvAndLimitedInputDevice'
type TokenEndpointAuthMethod = 'none' | 'client_secret_post' | 'client_secret_basic' | 'mtls'
type GrantType = 'authorization_code' | 'pkce' | 'refresh_token' | 'client_credentials' | 'implicit' | 'password' | 'urn:ietf:params:oauth:grant-type:jwt-bearer' | 'urn:ietf:params:oauth:grant-type:device_code'

// https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata
type OAuth2Client = {
  id: string
  applicationType: ApplicationType
  grantTypes: GrantType[]
  tokenEndpointAuthMethod: TokenEndpointAuthMethod

  name: string
  allowedCorsOrigins: string[]
  scopes: string[]
  audiences: string[]
  redirectUris: string[]
  postLogoutRedirectUris: string[]

  contacts: string[]
  uri?: string
  policyUri?: string
  tosUri?: string
  logoUri?: string
}

type TestIdClient = {
  clientId: string
  clientSecret: string
  client: OAuth2Client
}

type Client = {
  client: OAuth2Client
  testIdClient?: TestIdClient
  url: string
}
